package com.promise.cn.model;

// Generated 2010-10-29 9:17:56 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * PbUser generated by hbm2java
 */
@Entity
@Table(name = "pb_user", catalog = "pbsoft")
public class PbUser implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private String name;
	private String password;

	public PbUser() {
	}

	public PbUser(String id, String name, String password) {
		this.id = id;
		this.name = name;
		this.password = password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 40)
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid",strategy="uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
